spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tennis
    username: root
    password: yuexinisme
server:
  port: 8099

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl